import numpy as np
matrix=np.random.randint(10,size=(2,2))
print("Random genereated Matrix")
print(matrix)
det=np.linalg.det(matrix)
print("Determinant of matrix: ",det)
inverse=np.linalg.inv(matrix)
print("Inverse of the Matrix:\n",inverse)
rank=np.linalg.matrix_rank(matrix)
print("Rank of the Matrix: ",rank)
EVal,EVect = np.linalg.eig(matrix)
print("Eigen Value:")
print(EVal)
print("Eigen Vector")
print(EVect)
array_1D=matrix.flatten()
print("Transform Matrix in 1_D array: ",array_1D)
